require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LocationRelationsController do

  def mock_location_relation(stubs={})
    @mock_location_relation ||= mock_model(LocationRelation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all location_relations as @location_relations" do
      LocationRelation.stub(:all) { [mock_location_relation] }
      get :index
      assigns(:location_relations).should eq([mock_location_relation])
    end
  end

  describe "GET show" do
    it "assigns the requested location_relation as @location_relation" do
      LocationRelation.stub(:find).with("37") { mock_location_relation }
      get :show, :id => "37"
      assigns(:location_relation).should be(mock_location_relation)
    end
  end

  describe "GET new" do
    it "assigns a new location_relation as @location_relation" do
      LocationRelation.stub(:new) { mock_location_relation }
      get :new
      assigns(:location_relation).should be(mock_location_relation)
    end
  end

  describe "GET edit" do
    it "assigns the requested location_relation as @location_relation" do
      LocationRelation.stub(:find).with("37") { mock_location_relation }
      get :edit, :id => "37"
      assigns(:location_relation).should be(mock_location_relation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created location_relation as @location_relation" do
        LocationRelation.stub(:new).with({'these' => 'params'}) { mock_location_relation(:save => true) }
        post :create, :location_relation => {'these' => 'params'}
        assigns(:location_relation).should be(mock_location_relation)
      end

      it "redirects to the created location_relation" do
        LocationRelation.stub(:new) { mock_location_relation(:save => true) }
        post :create, :location_relation => {}
        response.should redirect_to(location_relation_url(mock_location_relation))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved location_relation as @location_relation" do
        LocationRelation.stub(:new).with({'these' => 'params'}) { mock_location_relation(:save => false) }
        post :create, :location_relation => {'these' => 'params'}
        assigns(:location_relation).should be(mock_location_relation)
      end

      it "re-renders the 'new' template" do
        LocationRelation.stub(:new) { mock_location_relation(:save => false) }
        post :create, :location_relation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested location_relation" do
        LocationRelation.stub(:find).with("37") { mock_location_relation }
        mock_location_relation.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :location_relation => {'these' => 'params'}
      end

      it "assigns the requested location_relation as @location_relation" do
        LocationRelation.stub(:find) { mock_location_relation(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:location_relation).should be(mock_location_relation)
      end

      it "redirects to the location_relation" do
        LocationRelation.stub(:find) { mock_location_relation(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(location_relation_url(mock_location_relation))
      end
    end

    describe "with invalid params" do
      it "assigns the location_relation as @location_relation" do
        LocationRelation.stub(:find) { mock_location_relation(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:location_relation).should be(mock_location_relation)
      end

      it "re-renders the 'edit' template" do
        LocationRelation.stub(:find) { mock_location_relation(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested location_relation" do
      LocationRelation.stub(:find).with("37") { mock_location_relation }
      mock_location_relation.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the location_relations list" do
      LocationRelation.stub(:find) { mock_location_relation }
      delete :destroy, :id => "1"
      response.should redirect_to(location_relations_url)
    end
  end

end
